services:
  sleevenotes:
    image: ghcr.io/sidtheturtle/sleevenotes:latest
    container_name: sleevenotes
    ports:
      - "2026:2026"
    volumes:
      - data:/data
    restart: unless-stopped

volumes:
  data:
    name: sleevenotes_data
